topic:
  name: vinaylogics-avro
server:
  port: 8181

spring:
  devtools:
    restart:
      enabled: false
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"
    consumer:
      group-id: "vinaylogics-new"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      auto-offset-reset: "earliest"
      properties:
        spring.json.trusted.packages: "com.vinaylogics.dto"
        spring.deserializer.key.delegate.class: "org.apache.kafka.common.serialization.StringDeserializer"
        spring.deserializer.value.delegate.class: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
        schema:
          registry:
            url: "http://127.0.0.1:8081"
        specific:
          avro:
            reader: "true"

